apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadujix3192-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadujix3192-tenant-component
    app.kubernetes.io/part-of: loadujix3192-tenant-app
  name: loadujix3192-tenant-component
  namespace: loadujix3192-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadujix3192-tenant-component
    weight: null
status: {}
